platform :ios, '9.0'

target 'TabvnCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TabvnCamera

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
  ]

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'TabvnCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TabvnCamera-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TabvnCamera-tvOS

  target 'TabvnCamera-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end